include $(GOROOT)/src/Make.inc

TARG=python
GOFILES=\
	scanner.go\
	bytecode.go\
	machine.go\
	object.go\
	module_builtin.go\
	int_builtin.go\
	float_builtin.go\
	string_builtin.go\
		
include $(GOROOT)/src/Make.pkg
